import type { CmsResourceConfig } from '../types/cms';

export const cmsResourceConfigs: CmsResourceConfig[] = [
  {
    key: 'projects',
    table: 'projects',
    title: 'Projetos',
    singular: 'projeto',
    description: 'Cadastre cases, links, imagens e destaque na vitrine pública.',
    initialRecord: {
      title: '',
      slug: '',
      category: '',
      description: '',
      image_url: '',
      live_url: '',
      repository_url: '',
      sort_order: 0,
      is_featured: true,
      is_published: true,
    },
    fields: [
      { name: 'title', label: 'Título', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text', required: true },
      { name: 'category', label: 'Categoria', type: 'text', required: true },
      { name: 'description', label: 'Descrição', type: 'textarea', required: true },
      { name: 'image_url', label: 'Imagem', type: 'url', required: true },
      { name: 'live_url', label: 'Link público', type: 'url' },
      { name: 'repository_url', label: 'Repositório', type: 'url' },
      { name: 'sort_order', label: 'Ordem', type: 'number' },
      { name: 'is_featured', label: 'Destacado', type: 'checkbox' },
      { name: 'is_published', label: 'Publicado', type: 'checkbox' },
    ],
    getTitle: (record) => String(record.title ?? 'Projeto sem título'),
    getSubtitle: (record) => String(record.category ?? 'Sem categoria'),
  },
  {
    key: 'technologies',
    table: 'technologies',
    title: 'Tecnologias',
    singular: 'tecnologia',
    description: 'Controle stack, ícone, categoria e ordem do carrossel.',
    initialRecord: {
      name: '',
      icon_url: '',
      category: '',
      sort_order: 0,
      is_featured: true,
    },
    fields: [
      { name: 'name', label: 'Nome', type: 'text', required: true },
      { name: 'icon_url', label: 'Ícone', type: 'url', required: true },
      { name: 'category', label: 'Categoria', type: 'text', required: true },
      { name: 'sort_order', label: 'Ordem', type: 'number' },
      { name: 'is_featured', label: 'Exibir no site', type: 'checkbox' },
    ],
    getTitle: (record) => String(record.name ?? 'Tecnologia sem nome'),
    getSubtitle: (record) => String(record.category ?? 'Sem categoria'),
  },
  {
    key: 'certificates',
    table: 'certificates',
    title: 'Certificados',
    singular: 'certificado',
    description: 'Registre cursos, instituições, datas e links de credencial.',
    initialRecord: {
      title: '',
      issuer: '',
      issued_at: '',
      credential_url: '',
      image_url: '',
      sort_order: 0,
      is_published: true,
    },
    fields: [
      { name: 'title', label: 'Título', type: 'text', required: true },
      { name: 'issuer', label: 'Emissor', type: 'text', required: true },
      { name: 'issued_at', label: 'Data', type: 'date' },
      { name: 'credential_url', label: 'Credencial', type: 'url' },
      { name: 'image_url', label: 'Imagem', type: 'url' },
      { name: 'sort_order', label: 'Ordem', type: 'number' },
      { name: 'is_published', label: 'Publicado', type: 'checkbox' },
    ],
    getTitle: (record) => String(record.title ?? 'Certificado sem título'),
    getSubtitle: (record) => String(record.issuer ?? 'Sem emissor'),
  },
  {
    key: 'experiences',
    table: 'experiences',
    title: 'Experiências',
    singular: 'experiência',
    description: 'Atualize trajetória profissional, estudos e experiências próprias.',
    initialRecord: {
      company: '',
      role: '',
      location: '',
      start_date: '',
      end_date: '',
      description: '',
      type: 'personal',
      sort_order: 0,
      is_published: true,
    },
    fields: [
      { name: 'company', label: 'Empresa ou contexto', type: 'text', required: true },
      { name: 'role', label: 'Cargo', type: 'text', required: true },
      { name: 'location', label: 'Local', type: 'text', required: true },
      { name: 'start_date', label: 'Início', type: 'date', required: true },
      { name: 'end_date', label: 'Fim', type: 'date' },
      { name: 'description', label: 'Descrição', type: 'textarea', required: true },
      {
        name: 'type',
        label: 'Tipo',
        type: 'select',
        options: [
          { label: 'Tempo integral', value: 'full-time' },
          { label: 'Freelance', value: 'freelance' },
          { label: 'Estudo', value: 'study' },
          { label: 'Pessoal', value: 'personal' },
        ],
      },
      { name: 'sort_order', label: 'Ordem', type: 'number' },
      { name: 'is_published', label: 'Publicado', type: 'checkbox' },
    ],
    getTitle: (record) => String(record.role ?? 'Experiência sem cargo'),
    getSubtitle: (record) => String(record.company ?? 'Sem contexto'),
  },
];

