import { certificateCategoryOptions, DEFAULT_CERTIFICATE_CATEGORY } from './certificateCategories';
import type { CmsResourceConfig } from '../types/cms';

export const cmsResourceConfigs: CmsResourceConfig[] = [
  {
    key: 'projects',
    table: 'projects',
    title: 'Projetos',
    singular: 'projeto',
    description: 'Cadastre cases, links, imagens e destaque na vitrine pública.',
    initialRecord: {
      title: '',
      slug: '',
      short_description: '',
      description: '',
      cover_url: '',
      github_url: '',
      deploy_url: '',
      status: 'finalizado',
      featured: true,
      active: true,
      display_order: 0,
      started_at: '',
      completed_at: '',
    },
    fields: [
      { name: 'title', label: 'Título', type: 'text', required: true, placeholder: 'KiTenis' },
      { name: 'slug', label: 'Slug', type: 'text', required: true, placeholder: 'kitenis' },
      { name: 'short_description', label: 'Chamada curta', type: 'text', placeholder: 'E-commerce' },
      { name: 'description', label: 'Descrição', type: 'textarea', placeholder: 'Resumo do problema, solução e resultado do projeto.' },
      {
        name: 'cover_url',
        label: 'Imagem do projeto',
        type: 'text',
      },
      { name: 'deploy_url', label: 'Projeto online', type: 'url', placeholder: 'https://projeto.vercel.app' },
      { name: 'github_url', label: 'Repositorio GitHub', type: 'url', placeholder: 'https://github.com/usuario/repositorio' },
      { name: 'status', label: 'Status', type: 'text', placeholder: 'finalizado' },
      { name: 'featured', label: 'Destacado', type: 'checkbox' },
      { name: 'active', label: 'Ativo no portfólio', type: 'checkbox' },
      { name: 'display_order', label: 'Ordem', type: 'number' },
      { name: 'started_at', label: 'Início', type: 'date' },
      { name: 'completed_at', label: 'Conclusão', type: 'date' },
    ],
    getTitle: (record) => String(record.title ?? 'Projeto sem título'),
    getSubtitle: (record) => String(record.short_description ?? record.status ?? 'Sem chamada'),
  },
  {
    key: 'technologies',
    table: 'technologies',
    title: 'Tecnologias',
    singular: 'tecnologia',
    description: 'Controle stack, ícone, categoria, nível e ordem do carrossel.',
    initialRecord: {
      name: '',
      category: '',
      level: '',
      icon_url: '',
      active: true,
      display_order: 0,
    },
    fields: [
      { name: 'name', label: 'Nome', type: 'text', required: true, placeholder: 'React' },
      { name: 'category', label: 'Categoria', type: 'text', placeholder: 'front-end' },
      { name: 'level', label: 'Nível', type: 'text', placeholder: 'intermediate' },
      {
        name: 'icon_url',
        label: 'Ícone da tecnologia',
        type: 'url',
        placeholder: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg',
        hint: 'Use uma URL SVG/PNG servida pelo app ou por uma CDN confiável. Se ficar vazio, o site usa um ícone padrão.',
      },
      { name: 'active', label: 'Exibir no site', type: 'checkbox' },
      { name: 'display_order', label: 'Ordem', type: 'number' },
    ],
    getTitle: (record) => String(record.name ?? 'Tecnologia sem nome'),
    getSubtitle: (record) => String(record.category ?? record.level ?? 'Sem categoria'),
  },
  {
    key: 'certificates',
    table: 'certificates',
    title: 'Certificados',
    singular: 'certificado',
    description: 'Registre cursos, instituições, datas e links de credencial.',
    initialRecord: {
      title: '',
      institution: '',
      category: DEFAULT_CERTIFICATE_CATEGORY,
      certificate_url: '',
      workload: '',
      completed_at: '',
      active: true,
      featured: false,
      display_order: 0,
    },
    fields: [
      { name: 'title', label: 'Título', type: 'text', required: true, placeholder: 'React: desenvolvendo com JavaScript' },
      { name: 'institution', label: 'Instituição', type: 'text', placeholder: 'Alura' },
      {
        name: 'category',
        label: 'Categoria',
        type: 'select',
        required: true,
        options: certificateCategoryOptions,
        defaultValue: DEFAULT_CERTIFICATE_CATEGORY,
      },
      { name: 'certificate_url', label: 'Link do certificado', type: 'url', placeholder: 'https://exemplo.com/certificado' },
      { name: 'workload', label: 'Carga horária', type: 'text', placeholder: '32h' },
      { name: 'completed_at', label: 'Conclusão', type: 'date' },
      { name: 'active', label: 'Ativo no portfólio', type: 'checkbox' },
      { name: 'featured', label: 'Destacar certificado', type: 'checkbox' },
      { name: 'display_order', label: 'Ordem', type: 'number' },
    ],
    getTitle: (record) => String(record.title ?? 'Certificado sem título'),
    getSubtitle: (record) => String(record.institution ?? record.category ?? 'Sem instituição'),
  },
  {
    key: 'experiences',
    table: 'experiences',
    title: 'Experiências',
    singular: 'experiência',
    description: 'Atualize trajetória profissional, estudos e experiências próprias.',
    initialRecord: {
      role: '',
      company: '',
      start_date: '',
      end_date: '',
      current: false,
      description: '',
      active: true,
      display_order: 0,
    },
    fields: [
      { name: 'role', label: 'Cargo', type: 'text', required: true, placeholder: 'Desenvolvedor Full Stack' },
      { name: 'company', label: 'Empresa ou contexto', type: 'text', placeholder: 'Projetos próprios' },
      { name: 'start_date', label: 'Início', type: 'date' },
      { name: 'end_date', label: 'Fim', type: 'date' },
      { name: 'current', label: 'Atual', type: 'checkbox' },
      { name: 'description', label: 'Descrição', type: 'textarea', placeholder: 'Principais responsabilidades, tecnologias e entregas.' },
      { name: 'active', label: 'Ativo', type: 'checkbox' },
      { name: 'display_order', label: 'Ordem', type: 'number' },
    ],
    getTitle: (record) => String(record.role ?? 'Experiência sem cargo'),
    getSubtitle: (record) => String(record.company ?? 'Sem contexto'),
  },
];
