import type { CmsResourceConfig } from '../types/cms';

export const cmsResourceConfigs: CmsResourceConfig[] = [
  {
    key: 'projects',
    table: 'projects',
    title: 'Projetos',
    singular: 'projeto',
    description: 'Cadastre cases, links, imagens e destaque na vitrine pública.',
    initialRecord: {
      title: '',
      slug: '',
      short_description: '',
      description: '',
      cover_url: '',
      github_url: '',
      deploy_url: '',
      status: 'finalizado',
      featured: true,
      active: true,
      display_order: 0,
      started_at: '',
      completed_at: '',
    },
    fields: [
      { name: 'title', label: 'Título', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text', required: true },
      { name: 'short_description', label: 'Chamada curta', type: 'text' },
      { name: 'description', label: 'Descrição', type: 'textarea' },
      { name: 'cover_url', label: 'Imagem de capa', type: 'url' },
      { name: 'github_url', label: 'GitHub', type: 'url' },
      { name: 'deploy_url', label: 'Deploy', type: 'url' },
      { name: 'status', label: 'Status', type: 'text' },
      { name: 'featured', label: 'Destacado', type: 'checkbox' },
      { name: 'active', label: 'Ativo', type: 'checkbox' },
      { name: 'display_order', label: 'Ordem', type: 'number' },
      { name: 'started_at', label: 'Início', type: 'date' },
      { name: 'completed_at', label: 'Conclusão', type: 'date' },
    ],
    getTitle: (record) => String(record.title ?? 'Projeto sem título'),
    getSubtitle: (record) => String(record.short_description ?? record.status ?? 'Sem chamada'),
  },
  {
    key: 'technologies',
    table: 'technologies',
    title: 'Tecnologias',
    singular: 'tecnologia',
    description: 'Controle stack, ícone, categoria, nível e ordem do carrossel.',
    initialRecord: {
      name: '',
      category: '',
      level: '',
      icon_url: '',
      active: true,
      display_order: 0,
    },
    fields: [
      { name: 'name', label: 'Nome', type: 'text', required: true },
      { name: 'category', label: 'Categoria', type: 'text' },
      { name: 'level', label: 'Nível', type: 'text' },
      { name: 'icon_url', label: 'Ícone', type: 'url' },
      { name: 'active', label: 'Exibir no site', type: 'checkbox' },
      { name: 'display_order', label: 'Ordem', type: 'number' },
    ],
    getTitle: (record) => String(record.name ?? 'Tecnologia sem nome'),
    getSubtitle: (record) => String(record.category ?? record.level ?? 'Sem categoria'),
  },
  {
    key: 'certificates',
    table: 'certificates',
    title: 'Certificados',
    singular: 'certificado',
    description: 'Registre cursos, instituições, datas e links de credencial.',
    initialRecord: {
      title: '',
      institution: '',
      category: '',
      certificate_url: '',
      image_url: '',
      workload: '',
      completed_at: '',
      active: true,
      display_order: 0,
    },
    fields: [
      { name: 'title', label: 'Título', type: 'text', required: true },
      { name: 'institution', label: 'Instituição', type: 'text' },
      { name: 'category', label: 'Categoria', type: 'text' },
      { name: 'certificate_url', label: 'Credencial', type: 'url' },
      { name: 'image_url', label: 'Imagem', type: 'url' },
      { name: 'workload', label: 'Carga horária', type: 'text' },
      { name: 'completed_at', label: 'Conclusão', type: 'date' },
      { name: 'active', label: 'Ativo', type: 'checkbox' },
      { name: 'display_order', label: 'Ordem', type: 'number' },
    ],
    getTitle: (record) => String(record.title ?? 'Certificado sem título'),
    getSubtitle: (record) => String(record.institution ?? record.category ?? 'Sem instituição'),
  },
  {
    key: 'experiences',
    table: 'experiences',
    title: 'Experiências',
    singular: 'experiência',
    description: 'Atualize trajetória profissional, estudos e experiências próprias.',
    initialRecord: {
      role: '',
      company: '',
      start_date: '',
      end_date: '',
      current: false,
      description: '',
      active: true,
      display_order: 0,
    },
    fields: [
      { name: 'role', label: 'Cargo', type: 'text', required: true },
      { name: 'company', label: 'Empresa ou contexto', type: 'text' },
      { name: 'start_date', label: 'Início', type: 'date' },
      { name: 'end_date', label: 'Fim', type: 'date' },
      { name: 'current', label: 'Atual', type: 'checkbox' },
      { name: 'description', label: 'Descrição', type: 'textarea' },
      { name: 'active', label: 'Ativo', type: 'checkbox' },
      { name: 'display_order', label: 'Ordem', type: 'number' },
    ],
    getTitle: (record) => String(record.role ?? 'Experiência sem cargo'),
    getSubtitle: (record) => String(record.company ?? 'Sem contexto'),
  },
];
